import Link from "next/link"
import { ArrowUpRight, Play } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { CaseStudyCarousel } from "@/components/case-study/carousel"
import { placeholderSlides, type CaseStudy } from "@/data/case-studies"

export function CaseStudyTemplate({ study, related }: { study: CaseStudy; related: CaseStudy[] }) {
  return <main className="mx-auto max-w-6xl px-5 pb-20 md:px-8">
    <Link href="/#projects" className="mt-10 inline-flex text-xs text-muted-foreground transition-colors hover:text-primary">← Back to work</Link>
    <section className="mt-8 rounded-3xl bg-primary px-6 py-10 text-primary-foreground md:px-12 md:py-16">
      <div className="flex flex-col gap-10 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.28em]">{study.eyebrow}</p><h1 className="mt-5 text-5xl font-medium tracking-[-0.06em] md:text-7xl">{study.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 opacity-80 md:text-lg">{study.tagline}</p></div><Badge variant="outline" className="w-fit border-primary-foreground/40 bg-transparent text-primary-foreground">{study.category}</Badge></div>
    </section>
    <section className="py-10 md:py-14"><CaseStudyCarousel slides={placeholderSlides} title={study.title} /></section>
    <section className="grid gap-8 border-y border-border py-12 md:grid-cols-[0.7fr_1.3fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">At a glance</p><h2 className="mt-4 text-4xl tracking-[-0.05em] md:text-5xl">What I<br /><em className="text-primary">delivered.</em></h2></div><div className="grid gap-3">{[["01", "Project goal", study.goal], ["02", "My contribution", study.contribution], ["03", "Result", study.result]].map(([number, label, copy]) => <article key={number} className="rounded-2xl border border-border bg-card p-6"><span className="font-mono text-[10px] text-primary">{number}</span><h3 className="mt-4 text-xl font-medium">{label}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></section>
    <section className="py-14"><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">Selected development</p><h2 className="mt-4 max-w-2xl text-4xl tracking-[-0.05em] md:text-5xl">The work behind the <em className="text-primary">experience.</em></h2><div className="mt-8 grid overflow-hidden rounded-2xl border border-border md:grid-cols-2">{study.features.map((feature, index) => <article key={feature.title} className="border-border bg-card p-6 even:border-t md:border-r md:odd:border-b md:even:border-t-0 md:nth-[2n]:border-r-0"><span className="font-mono text-[10px] text-primary">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 text-lg font-medium">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{feature.description}</p></article>)}</div></section>
    <section className="border-t border-border py-8"><div className="grid gap-5 md:grid-cols-3">{[["Role", study.role], ["Focus", study.focus], ["Delivery", study.delivery]].map(([label, value]) => <div key={label}><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">{label}</p><p className="mt-2 text-sm font-medium">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{study.techStack.map((tech) => <Badge key={tech} variant="outline" className="rounded-full px-3 py-1 text-xs font-normal">{tech}</Badge>)}</div></section>
    <section className="py-12"><div className="relative flex aspect-video flex-col items-center justify-center gap-3 overflow-hidden rounded-2xl border border-border bg-card text-center"><Play className="size-8 text-primary" /><p className="text-lg font-medium">Demo video coming soon</p><p className="text-sm text-muted-foreground">This placeholder is ready for a video URL.</p></div></section>
    <section className="border-t border-border py-12"><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">Keep exploring</p><div className="mt-6 grid gap-4 md:grid-cols-2">{related.map((item) => <Link key={item.slug} href={`/work/${item.slug}`} className="group rounded-2xl border border-border bg-card p-6 transition-colors hover:border-primary/50"><p className="text-sm text-muted-foreground">{item.category}</p><h3 className="mt-3 text-2xl tracking-tight">{item.title} <ArrowUpRight className="inline size-5 text-primary transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.tagline}</p></Link>)}</div></section>
    <section className="rounded-3xl border border-primary/30 bg-primary/10 px-6 py-10 md:px-10"><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">Have a similar challenge?</p><h2 className="mt-4 text-4xl tracking-[-0.05em] md:text-5xl">Let&apos;s build <em className="text-primary">something useful.</em></h2><Button asChild className="mt-6"><a href="mailto:komalraza.dev@gmail.com">Start a conversation</a></Button></section>
  </main>
}
